sonar.projectKey=Aezule_money_talk-api
sonar.organization=aezule
sonar.host.url=https://sonarcloud.io

sonar.sources=src
sonar.tests=src,test
sonar.test.inclusions=**/*.spec.ts,**/*.e2e-spec.ts

sonar.exclusions=**/node_modules/**, **/dist/**, **/coverage/**, prisma/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8